# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16"
  i386: "ghcr.io/home-assistant/i386-base-python:3.10-alpine3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: pixoo-rest"
  org.opencontainers.image.description: "This Add-on runs pixoo-rest, a RESTful API to easily interact with the Wi-Fi enabled Divoom Pixoo devices."
  org.opencontainers.image.source: "https://github.com/kmplngj/ha-addons"
  org.opencontainers.image.licenses: "MIT License"
