# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.20"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.20"
  i386: "ghcr.io/home-assistant/i386-base-python:3.13-alpine3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Pixoo REST"
  org.opencontainers.image.description: "RESTful API to interact with Divoom Pixoo LED displays with automatic discovery and Home Assistant integration"
  org.opencontainers.image.source: "https://github.com/kmplngj/ha-addons"
  org.opencontainers.image.version: "0.1.0"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.documentation: "https://github.com/kmplngj/ha-addons/blob/main/pixoo-rest/DOCS.md"
